"use client"

import * as React from "react"
import { Edit, X, Plus } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Drawer,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
} from "@/components/ui/drawer"
import { ScrollArea } from "@/components/ui/scroll-area"
import type { ApiClient, TableMetadata } from "@/lib/api"

interface EditItemDrawerProps {
  table: TableMetadata
  apiClient: ApiClient
  open: boolean
  onClose: () => void
  onItemAdded: (item: any) => void
}

export function AddItemDrawer({ table, apiClient, open, onClose, onItemAdded }: EditItemDrawerProps) {
  const [tableFields, setTableFields] = React.useState<any>([])
  const [formData, setFormData] = React.useState<any>({})
  const [isLoading, setIsLoading] = React.useState(false)
  const [isViewType, setIsViewIsViewType] = React.useState(false)
  const [hasUnsavedChanges, setHasUnsavedChanges] = React.useState(false)

  React.useEffect(() => {
    if (open) {
      setFormData({})
      setHasUnsavedChanges(false)
      setTableFields(table.schema?.fields.filter(f => !isSystemGeneratedField(f)))
      setIsViewIsViewType(table?.type === "view")
    }
  }, [open])

  const handleSubmit = async () => {
    setIsLoading(true)
    try {
      const createdItem = await apiClient.call<any>(`/api/v1/${table.name}`, {
        method: "POST",
        body: JSON.stringify(formData),
      })
      onItemAdded(createdItem)
      onClose()
    } catch (error) {
      console.error("Failed to update item:", error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleFieldChange = (fieldName: string, value: string) => {
    setFormData((prev: any) => ({
      ...prev,
      [fieldName]: value,
    }))
    setHasUnsavedChanges(true)
  }

  const isSystemGeneratedField = (field: any) => {
    return field.system && ["id", "created", "updated"].includes(field.name)
  }

  const handleClose = () => {
    if (hasUnsavedChanges) {
      if (confirm("You have unsaved changes. Are you sure you want to close?")) {
        setHasUnsavedChanges(false)
        onClose()
      }
    } else {
      onClose()
    }
  }

  return (
    <Drawer open={open} onOpenChange={handleClose}>
      <DrawerContent side="right" className="w-[700px] max-w-[95vw]">
        <DrawerHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Edit className="h-5 w-5" />
              <DrawerTitle>Add a Record</DrawerTitle>
            </div>
            <Button variant="ghost" size="sm" onClick={handleClose}>
              <X className="h-4 w-4" />
            </Button>
          </div>
          <DrawerDescription>Create a new record in {table.name} table</DrawerDescription>
        </DrawerHeader>

        <div className="flex-1 overflow-hidden">
          <ScrollArea className="h-full">
            <div className="p-6 space-y-6">
              <p className="text-sm text-muted-foreground">Autogenerated fields for this table: `id`, `created` and `updated`</p>
              {tableFields?.map((field: any) => (
                <div key={field.name} className="space-y-2">
                  <Label htmlFor={field.name} className="text-sm font-medium capitalize">
                    {field.name}
                    {(field.required || field.system) && <span className="text-red-500 ml-1">*</span>}
                  </Label>
                  <Input
                    id={field.name}
                    type={
                      field.name === "password"
                        ? "password"
                        : field.type === "date" ? "datetime-local" : "text"
                    }
                    value={formData[field.name] || ""}
                    onChange={(e) => handleFieldChange(field.name, e.target.value)}
                    disabled={(field.type === "view" || isSystemGeneratedField(field))}
                    className={`w-full ${(field.type === "view" || isSystemGeneratedField(field)) ? "bg-muted" : ""}`}
                    placeholder={`Enter ${field.name}`}
                  />
                </div>
              ))}

              {(!tableFields || tableFields.length === 0) &&
                <p className="text-xs text-muted-foreground">No additional fields for input, proceed to create the record.</p>
              }
            </div>
          </ScrollArea>
        </div>

        <DrawerFooter>
          <div className="flex gap-3">
            <Button variant="outline" onClick={handleClose} className="flex-1">
              Cancel
            </Button>
            <Button onClick={handleSubmit} disabled={isLoading || isViewType} className="flex-1">
              {isLoading ? "Creating..." : "Create Record"}
            </Button>
          </div>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  )
}
